name: stitch_utils
version: 0.3.1
config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"

require-dbt-version: [">=1.2.0", "<2.0.0"]
